AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  WebApp (Route 53 -> CloudFront -> S3)

Parameters:
  Subdomain:
    Default: ""
    Type: String
  Domain:
    Default: bestpicture.link
    Type: String
  Environment:
    Default: prod
    Type: String
    AllowedValues: ["prod", "dev", "test"]
    ConstraintDescription: must specify prod, dev, or test.
  HostedZoneId:
    Description: Hosted Zone ID in Route 53
    Default: Z06329612CU86LT1FXZ7C
    Type: String
  CertificateArn:
    Description: Certificate ARN from AWS Certificate Manager
    Default: arn:aws:acm:us-east-1:699488813374:certificate/df4233c6-652d-46b9-8b19-3718a3e476c8
    Type: String

Conditions:
  NoSubdomain: !Equals [!Ref Subdomain, ""]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !If [NoSubdomain, !Sub "${Domain}", !Sub "${Subdomain}.${Domain}"]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Subdomain
          Value: !Ref Subdomain
        - Key: Project
          Value: bestpicture
  PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: AllowPublicReadAccess
        Version: "2012-10-17"
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref "S3Bucket"
                - "/*"
            Principal: "*"
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: S3Bucket
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: PriceClass_100
        Aliases:
          - !Ref S3Bucket
        HttpVersion: http2
        DefaultRootObject: index.html
        Origins:
          #https://stackoverflow.com/a/58423033/602860
          - DomainName: !GetAtt S3Bucket.RegionalDomainName
            Id: !Ref S3Bucket
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: !Ref CertificateArn
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: !Ref S3Bucket
          ForwardedValues:
            QueryString: false
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 60
          Compress: true
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 400
            ResponseCode: 200
            ResponsePagePath: /
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Subdomain
          Value: !Ref Subdomain
        - Key: Project
          Value: bestpicture
  ARecordSet:
    Type: AWS::Route53::RecordSet
    DependsOn: CloudFrontDistribution
    Properties:
      Name: !Ref S3Bucket
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        # https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/quickref-route53.html
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref HostedZoneId

Outputs:
  DomainName:
    Value: !Ref ARecordSet
  DistributionId:
    Value: !Ref CloudFrontDistribution
  BucketName:
    Value: !Ref S3Bucket
  Url:
    Value: !Join
      - ""
      - - "https://"
        - !Ref ARecordSet
