AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Name:
    Type: String
  Environment:
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Join
        - "."
        - - !Ref Environment
          - !Ref Name
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  BucketName:
    Value: !Ref S3Bucket
